service: aws-serverless25

provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  stage: dev
  environment:
    API_ENDPOINT: "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}"
    CommentsTable: comments
    AdsTable: ads
    ChatsTable: chats
    ImagesBucket: aws-serverless25-images
    StaticSiteBucket: aws-serverless25-frontend

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CommentsTable}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.AdsTable}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ChatsTable}"
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - "arn:aws:s3:::${self:provider.environment.ImagesBucket}/*"
            - "arn:aws:s3:::${self:provider.environment.StaticSiteBucket}/*"

plugins:
  - serverless-s3-sync
  - serverless-finch
  
custom:
  finch:
    stage: ${opt:stage, self:provider.stage}
    variables:
      API_ENDPOINT: ${self:provider.environment.API_ENDPOINT}

  client:
    bucketName: aws-serverless25-frontend
    distributionFolder: web
    errorDocument: index.html
    include:
      - '*.html'
      - '*.css'
      - '*.js'
  s3Sync:
    - bucketName: aws-serverless25-frontend
      localDir: web

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:provider.stage}-api-datahack
        Description: API ${self:service}

    StaticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-serverless25-frontend
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    ImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-serverless25-images
        VersioningConfiguration:
          Status: Enabled

    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: comments
        AttributeDefinitions:
          - AttributeName: ad_id
            AttributeType: S
          - AttributeName: comment_id
            AttributeType: S
        KeySchema:
          - AttributeName: ad_id
            KeyType: HASH
          - AttributeName: comment_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    AdsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ads
        AttributeDefinitions:
          - AttributeName: ad_id
            AttributeType: S
        KeySchema:
          - AttributeName: ad_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ChatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chats
        AttributeDefinitions:
          - AttributeName: ad_id
            AttributeType: S
          - AttributeName: chat_id
            AttributeType: S
        KeySchema:
          - AttributeName: ad_id
            KeyType: HASH
          - AttributeName: chat_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  getApiEndpoint:
    handler: handler.get_api_endpoint
    events:
      - http:
          path: /get-api-endpoint
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  createAd:
    handler: handler.create_ad
    events:
      - http:
          path: /create-ad
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  listAds:
    handler: handler.list_ads
    events:
      - http:
          path: /list-ads
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  getAd:
    handler: handler.get_ad
    events:
      - http:
          path: /get-ad
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  createComment:
    handler: handler.create_comment
    events:
      - http:
          path: /create-comment
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  getComments:
    handler: handler.get_comments
    events:
      - http:
          path: /get-comments
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  createChatMessage:
    handler: handler.create_chat_message
    events:
      - http:
          path: /create-chat-message
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  getChats:
    handler: handler.get_chats
    events:
      - http:
          path: /get-chats
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false

  getChatMessages:
    handler: handler.get_chat_messages
    events:
      - http:
          path: /get-chat-messages
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
            allowCredentials: false
